### ISSUE TITLE
支持annimator和多材质

### ISSUE THREAD

**Issue by mic89** [chenjd/Render-Crowd-Of-Animated-Characters#1]
您好, fork了您的项目 根据我们项目的需求做了一些改动, 可以支持animator, 但是animationclip不能勾选legacy, 想知道animation制作时勾选legacy的作用, 另外我们项目的模型有多个材质, 扩展了一下支持多材质, 但是对应的drawcall也会多一些

**Comment by mic89** [comment]
还有一个问题是 Unity2017下 enable instancing不能开启 需要通过C#代码强制设置material.enableInstancing = true;

**Comment by chenjd** [comment]
hi。谢谢你的拓展。
如果可以的话，欢迎合并到我这里。
legacy是为了用unity的老动画系统Legacy Animation。
