### ISSUE TITLE
Known Issue - Unity 2021 not supported

### ISSUE THREAD

**Issue by chenjd** [chenjd/Render-Crowd-Of-Animated-Characters#13]
There seems to be some issues with this project in Unity 2021, as shown in the images below. I don't know what has changed in Unity, but I know it might take some time to fix.

## Unity 2020.3
![cat-2020](https://user-images.githubusercontent.com/5668352/175752247-0ed5b573-a854-454a-b1cb-df59f7015eeb.PNG)

## Unity 2021.3
![cat-2021](https://user-images.githubusercontent.com/5668352/175752251-155cd249-bbb5-4e28-843c-eab4fab8cade.PNG)

**Comment by dodoan-alt** [comment]
Re-bake the assets in Unity 2021 is fixing this issue. Was the vertex ordering changed? @chenjd

**Comment by chenjd** [comment]
Thanks for the info @dodoan-alt . will check it out. :)
