### ISSUE TITLE
我在ECS1.0中使用出现以下问题，请问这要怎么解决

### ISSUE THREAD

**Issue by oshellhahaha** [chenjd/Render-Crowd-Of-Animated-Characters#19]
## 在普通的Scene下，显示正常
![image](https://github.com/chenjd/Render-Crowd-Of-Animated-Characters/assets/30201320/4f6d037f-2365-4d7f-b359-87c7eb09d214)

## 在ECS的`SubScene`中，不能正常显示了并提示错误：
`A BatchDrawCommand is using a pass from the shader "chenjd/URP/AnimMapWithShadowShader" that is not SRP Batcher compatible. Reason: "Material property is found in another cbuffer than "UnityPerMaterial"" (_AnimLen)
This is not supported when rendering with a BatchRendererGroup (or Entities Graphics). MaterialID: 4 ("Bat_Fly Forward In Place.animMap"), MeshID: 1 ("Bat"), BatchID: 2.`

![image](https://github.com/chenjd/Render-Crowd-Of-Animated-Characters/assets/30201320/2221af82-990a-4d84-987e-d49cdfbbb578)

**Comment by storm1122** [comment]
@oshellhahaha 请教怎么解决的
