### ISSUE TITLE
Bake Prefab 顶点偏移的问题

### ISSUE THREAD

**Issue by wuxingogo** [chenjd/Render-Crowd-Of-Animated-Characters#2]
您好，我用原工程的Bake后，mesh的顶点有偏移，请问如何能归为原点呢

**Comment by wuxingogo** [comment]
在AnimMapBaker73行 this.skin.BakeMesh(m);之前加了一句this.skin.transform.position = Vector3.zero;问题解决了...sorry是我尝试太少了

**Comment by wuxingogo** [comment]
另外 AnimMapBakerWindow 38 39行代码重新编译后animMapShader将变空，导致我总是得到shader is null的错误...

**Comment by chenjd** [comment]
@wuxingogo ok,谢谢反馈。
