### ISSUE TITLE
AnimMapBaker window stops working on wrong character input in path

### ISSUE THREAD

**Issue by OlegDzhuraev** [chenjd/Render-Crowd-Of-Animated-Characters#20]
As title says, you can accidentally type character like `|` in path and whole window render breaks with errors like:

`ArgumentException: Illegal characters in path.System.IO.Path.Combine (System.String path1, System.String path2)`

Can be fixed only by restarting Editor/Triggering domain reload (recompile). I suggest to not use `static` fields in window code to allow user "fix" problems like this just by reopening window.

Error itself can be fixed by using `try...catch` block at least.

**Comment by chenjd** [comment]
Hi @OlegDzhuraev. Thanks for reaching out. Could you please make a PR for it? Thanks so much. :)

**Comment by OlegDzhuraev** [comment]
Added PR https://github.com/chenjd/Render-Crowd-Of-Animated-Characters/pull/21

**Comment by chenjd** [comment]
Thank you @OlegDzhuraev
