### ISSUE TITLE
Clicking bake with no feedback

### ISSUE THREAD

**Issue by luiginicastro** [chenjd/Render-Crowd-Of-Animated-Characters#7]
When I place my model in the prefab section and paste in a path for it to build, I get no feedback when I press Bake. There is no error message or anything telling me if or why it didn't work. Was wondering if there is a certain way my model needs to be for this to work since it works no problem when I use the foot soldier.

**Comment by luiginicastro** [comment]
I notice that when I go to upload my own model the program does not work but when I use the prefab provided in the package it does. Once i use the provided prefab I can then use my own item but it continues to make maps for the Footman_Blue.


https://user-images.githubusercontent.com/58125435/124802869-6e775e00-df26-11eb-820f-5bcb6488ac98.mp4

**Comment by chenjd** [comment]
Thanks for contacting, it's interesting. can you send your model in this video to me (via email)?

**Comment by luiginicastro** [comment]
> 
> 
> Thanks for contacting, it's interesting. can you send your model in this video to me (via email)?

Yep! I'll email it over right now.

**Comment by chenjd** [comment]
Hi Luigi,

Just checked your model. I found that the animation type of your model is not "Legacy". You should keep the animation is "Legacy" and use Animation component on your original prefab.

There is a bug regarding to your case actually, but it's a minor issue. It's that there are two materials on your model, and the baker only creates one material for the output prefab with anim-map. You can add the second material to the output manually.  I'll fix it in the future.
